name: CI/CD
on: [push]
jobs:
  publish:
    name: Publish PDF resumes
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          path: resume
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.RESUME_S3_BUCKET_REGION }}

      - name: Deploy resumes to S3 bucket
        run: cd resume/out; aws s3 sync . s3://${{ secrets.RESUME_S3_BUCKET }} --delete
      
      - name: Invalidate cloudfront cache
        run: aws cloudfront create-invalidation --distribution-id  ${{ secrets.PERSONAL_WEBSITE_CLOUDFRONT_DISTRIBUTION_ID }} --paths '/resume*.pdf'
         
          